fix typo for AND operator
redhat-et/ilab-on-ocp pull request #44
Opened 2024-09-30 15:29 UTC by JudeNiroshan

2024-09-30 15:37 UTC, leseb requested changes

2024-09-30 15:37 UTC, leseb commented on sdg/components.py
> +            + f'elif [ -n "{repo_pr}" and {repo_pr} -gt 0 ]; then '
```suggestion
            + f'elif [ -n "{repo_pr}" ] && [ {repo_pr} -gt 0 ]; then '
```

2024-10-01 08:01 UTC, JudeNiroshan commented on sdg/components.py
> +            + f'elif [ -n "{repo_pr}" and {repo_pr} -gt 0 ]; then '
Thanks! 👍🏽

2024-10-01 09:29 UTC, leseb approved these changes
LGTM!

2024-10-01 10:27 UTC, merged